---
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/truenas-system/configs/freshrss/config:/config
    ports:
      - 31006:80
    restart: unless-stopped
