services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 568:568
    network_mode: 'host'
    volumes:
      - /mnt/truenas-system/configs/jellyfin/config:/config
      - /mnt/truenas-system/configs/jellyfin/cache:/cache
      - type: bind
        source: /mnt/truenas-system/media
        target: /media
      # - type: bind
      #   source: /path/to/media2
      #   target: /media2
      #   read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tacoslinux.com
