version: '3'
services:
    db:
        image: postgres:15
        volumes:
            - /mnt/truenas-system/configs/joplindb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "31004:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://joplin.tacoslinux.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=0
            #- MAILER_HOST=smtp.gmail.com
            #- MAILER_PORT=465
            #- MAILER_SECURE=1
            #- MAILER_AUTH_USER=youremail@gmail.com
            #- MAILER_AUTH_PASSWORD=Y0urP@ssw0rd
            #- MAILER_NOREPLY_NAME=Joplin
            #- MAILER_NOREPLY_EMAIL=email@email.com
            
volumes:
  joplindb:
