version: '3'
services:
    app:
        image: joplin/server:latest
        ports:
            - "31005:22300"
        restart: unless-stopped
        networks:
            - postgres_postgres
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://joplin.tacoslinux.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=${POSTGRES_HOST}
            - MAILER_ENABLED=0
