services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '31004:81'
      - '443:443'
    volumes:
      - /mnt/truenas-system/configs/nginx-proxy-manager/data:/data
      - /mnt/truenas-system/configs/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
