---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Denver
      - VERSION=docker
      # - PLEX_CLAIM=
    volumes:
      - /mnt/truenas-system/configs/plex:/config
      - /mnt/truenas-system/media:/data
    restart: unless-stopped
