version: '3'
services:
    postgres:
        image: postgres:15
        volumes:
            - /mnt/truenas-system/configs/postgres:/var/lib/postgresql/data
        expose:
            - 5432
        restart: unless-stopped
        networks:
          - postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
networks:
  postgres:
