version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "31003:9091"
  volumes:
    - /mnt/truenas-system/media:/data # where transmission will store the data
    - /mnt/truenas-system/configs/transmission/:/config # where transmission-home is stored
  environment:
    - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
    - OPENVPN_CONFIG=${OPENVPN_CONFIG}
    - OPENVPN_USERNAME=${OPENVPN_USERNAME}
    - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    - LOCAL_NETWORK=${LOCAL_NETWORK}
